name: BortexelEconomy
main: ru.ruscalworld.bortexel.economy.BortexelEconomy
version: ${version}
author: RuscalWorld
api-version: '1.16'
commands:
    ecoreport:
        description: Основная команда
        aliases: [er]
        permission: economy.report
    price:
        description: Получить актуальную стоимость предмета по его идентификатору
        aliases: [getprice,стоимость]
    ruslan:
        description: Задать вопрос Руслану
        aliases: [ai,руслан]